# yaml-language-server: $schema=https://raw.githubusercontent.com/bitwizeshift/go-cli/refs/heads/master/command.schema.json
name: godoc2
summary: Generates detailed, rustdoc-style HTML documentation for Go modules
description: |
  godoc2 is a documentation generator for Go. It produces a static HTML site
  with the layout of rustdoc and more detail than the standard Go docs.

  Unlike standard godocs, godoc2 generates detailed pages per entity in Go,
  and includes backlinks, references, and other helpful details. Types show what
  interfaces they  implement that are part of the build hierarchy, interfaces
  show types that implement them, etc.

  Sites are generated to the --output directory (dist by default). The specified
  pattern on execution selects packages using Go's builtin package spec semantics.
  To select multiple modules at once, either name multiple package specs, or
  use `--workspace` to reference a `go.work` file and generate docs for each
  module.

  Note: modules and packages will load README.md or index.md files if no go
  package docs are available.

examples:
  - godoc2
  - godoc2 -o docs
  - godoc2 ./internal/...
  - godoc2 --verbose -o public ./...
  - godoc2 --workspace go.work
issue-url: https://github.com/bitwizeshift/godoc2/issues
