name: Continuous Integration

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    name: Deploy Docs
    uses: ./.github/workflows/godoc-deploy.yaml

  go-release:
    name: Release godoc2
    uses: ./.github/workflows/go-release.yaml
    with:
      version: snapshot
